# Generated by Django 2.2 on 2020-02-11 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='myclass',
            field=models.IntegerField(blank=True, help_text='班级', null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='political',
            field=models.IntegerField(choices=[(0, '群众'), (1, '共青团员'), (2, '中共预备党员'), (3, '中共党员'), (4, '其它党派')], default=0, help_text='政治面貌', verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, help_text='性别', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 16, 3, 33, 1364), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
