# Generated by Django 2.2 on 2020-02-15 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200215_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 17, 30, 14, 79162), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
