# Generated by Django 2.2 on 2020-02-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 6, 39, 962174), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
