# Generated by Django 2.2 on 2020-02-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200216_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 10, 18, 122806), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
