# Generated by Django 2.2 on 2020-02-18 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200217_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 46, 2, 854000), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
