# Generated by Django 2.2 on 2020-02-19 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200219_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='starttime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 12, 57, 37, 661976), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
