# Generated by Django 2.2 on 2020-02-19 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200219_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 13, 2, 56, 664088), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
