# Generated by Django 2.2 on 2020-02-19 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200219_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='regtime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 15, 12, 15, 144588), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
