# Generated by Django 2.2 on 2020-02-19 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200219_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 26, 58, 122952), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
