# Generated by Django 2.2 on 2020-03-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200310_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 9, 47, 308418), help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
