# Generated by Django 2.2 on 2020-02-10 11:35

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_created=True, help_text='创建时间', verbose_name='创建时间')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('registration_time', models.DateField(help_text='报名时间', verbose_name='报名时间')),
                ('activity_time', models.IntegerField(help_text='活动时长', verbose_name='活动时长')),
                ('link_phone', models.CharField(help_text='联系电话', max_length=11, verbose_name='联系电话')),
                ('link_pople', models.CharField(help_text='联系人', max_length=20, verbose_name='联系人')),
                ('activity_content', DjangoUeditor.models.UEditorField(blank=True, help_text='活动内容', null=True, verbose_name='活动内容')),
                ('people_count', models.IntegerField(default=100, help_text='招募人数', verbose_name='招募人数')),
                ('activity_starttime', models.DateTimeField(help_text='活动时间', verbose_name='活动时间')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核未通过'), (3, '报名中'), (4, '活动开始'), (5, '活动结束'), (6, '活动取消')], help_text='活动状态', verbose_name='活动状态')),
                ('updatetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('hot', models.IntegerField(default=0, help_text='热度', verbose_name='热度')),
            ],
            options={
                'verbose_name': '义工活动',
                'verbose_name_plural': '义工活动',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_created=True, help_text='创建时间', verbose_name='创建时间')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, help_text='活动内容', null=True, verbose_name='活动内容')),
                ('updatetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '社区',
                'verbose_name_plural': '社区',
            },
        ),
        migrations.CreateModel(
            name='Communitypic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, help_text='比赛结果', null=True, upload_to='historypic/', verbose_name='比赛结果')),
            ],
        ),
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_created=True, help_text='创建时间', verbose_name='创建时间')),
                ('title', models.CharField(help_text='题目', max_length=20, verbose_name='题目')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, help_text='活动内容', null=True, verbose_name='活动内容')),
                ('updatetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '历史活动',
                'verbose_name_plural': '历史活动',
            },
        ),
        migrations.CreateModel(
            name='HPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, help_text='比赛结果', null=True, upload_to='historypic/', verbose_name='比赛结果')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名', max_length=100, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='UserandActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(0, '差'), (1, '一般'), (2, '优秀')], default=2, help_text='等级', verbose_name='等级')),
                ('activity_time', models.IntegerField(default=5, help_text='义工时', verbose_name='义工时')),
                ('signtime', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 11, 35, 44, 56705), help_text='报名时间', verbose_name='报名时间')),
                ('activity', models.ForeignKey(help_text='活动', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activity.Ativity', verbose_name='活动')),
            ],
        ),
    ]
