# Generated by Django 2.2 on 2020-02-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userandactivity',
            name='organ',
            field=models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='user.Organ', verbose_name='组织'),
        ),
        migrations.AddField(
            model_name='userandactivity',
            name='user',
            field=models.ForeignKey(help_text='活动人', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='活动人'),
        ),
        migrations.AddField(
            model_name='hpic',
            name='histroy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histroy', to='activity.Histroy'),
        ),
        migrations.AddField(
            model_name='histroy',
            name='activity',
            field=models.OneToOneField(help_text='义工', on_delete=django.db.models.deletion.CASCADE, to='activity.Ativity', verbose_name='义工'),
        ),
        migrations.AddField(
            model_name='communitypic',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='activity.Community'),
        ),
        migrations.AddField(
            model_name='ativity',
            name='organ',
            field=models.ForeignKey(help_text='机构', on_delete=django.db.models.deletion.CASCADE, to='user.Organ', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='ativity',
            name='people',
            field=models.ForeignKey(help_text='报名人', on_delete=django.db.models.deletion.CASCADE, related_name='acivity', to=settings.AUTH_USER_MODEL, verbose_name='报名人'),
        ),
        migrations.AddField(
            model_name='ativity',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='报名人', null=True, related_name='my_match', through='activity.UserandActivity', to=settings.AUTH_USER_MODEL, verbose_name='报名人'),
        ),
    ]
