# Generated by Django 2.2 on 2020-02-15 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200211_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核未通过'), (3, '报名中'), (4, '活动开始'), (5, '活动结束'), (6, '活动取消')], default=0, help_text='活动状态', verbose_name='活动状态'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 16, 53, 1, 612282), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
