# Generated by Django 2.2 on 2020-02-16 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20200215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 6, 39, 969537), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='people',
            field=models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.CASCADE, related_name='acivity', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='activity_time',
            field=models.IntegerField(blank=True, help_text='义工时', null=True, verbose_name='义工时'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '差'), (1, '一般'), (2, '优秀')], help_text='等级', null=True, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 6, 39, 970534), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
