# Generated by Django 2.2 on 2020-02-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200216_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandactivity',
            name='organ',
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 10, 18, 127836), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 10, 18, 127836), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
