# Generated by Django 2.2 on 2020-02-16 18:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0008_auto_20200216_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 18, 4, 7, 776440), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.RemoveField(
            model_name='ativity',
            name='hot',
        ),
        migrations.AddField(
            model_name='ativity',
            name='hot',
            field=models.ManyToManyField(blank=True, help_text='喜欢人', null=True, related_name='my_like', to=settings.AUTH_USER_MODEL, verbose_name='喜欢人'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 18, 4, 7, 778435), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
