# Generated by Django 2.2 on 2020-02-16 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20200216_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativity',
            name='type',
            field=models.ForeignKey(blank=True, help_text='类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actiyity', to='activity.Type', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 18, 12, 46, 939545), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 18, 12, 46, 940577), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
