# Generated by Django 2.2 on 2020-02-17 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20200216_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativity',
            name='registration_endtime',
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 15, 39, 30, 320547), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核中'), (2, '待发布'), (3, '已发布'), (4, '报名中'), (5, '报名结束'), (6, '活动中'), (7, '活动结束'), (8, '活动取消'), (9, '时长已录入'), (10, '审核不通过')], default=0, help_text='活动状态', verbose_name='活动状态'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 15, 39, 30, 321544), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
