# Generated by Django 2.2 on 2020-02-17 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20200217_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 38, 41, 262980), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='communitypic',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='activity.Community'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 38, 41, 263979), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
