# Generated by Django 2.2 on 2020-02-17 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20200217_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='publishtime',
            field=models.DateTimeField(blank=True, help_text='发布时间', null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 55, 50, 412319), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 55, 50, 414313), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
