# Generated by Django 2.2 on 2020-02-17 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20200217_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 1, 57, 615035), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 1, 57, 618027), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 1, 57, 616032), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
