# Generated by Django 2.2 on 2020-02-17 22:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0015_auto_20200217_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='publishuser',
            field=models.ForeignKey(blank=True, help_text='发布者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 20, 16, 112128), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 20, 16, 116117), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 20, 16, 114123), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
