# Generated by Django 2.2 on 2020-02-18 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20200218_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 52, 334657), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 52, 336651), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 52, 336651), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hpic',
            name='histroy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='activity.Histroy'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 52, 335654), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
