# Generated by Django 2.2 on 2020-02-18 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20200218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 57, 174198), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 57, 177225), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 57, 176227), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 51, 57, 175232), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
