# Generated by Django 2.2 on 2020-02-18 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_auto_20200218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 53, 33, 933393), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 53, 33, 936350), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='communitypic',
            name='url',
            field=models.FileField(blank=True, help_text='比赛结果', null=True, upload_to='communitypic/', verbose_name='比赛结果'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 53, 33, 935352), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 20, 53, 33, 935352), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
