# Generated by Django 2.2 on 2020-02-19 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_auto_20200219_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 12, 57, 37, 671949), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 12, 57, 37, 674941), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 12, 57, 37, 673944), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 12, 57, 37, 673944), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
