# Generated by Django 2.2 on 2020-02-19 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_auto_20200219_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativity',
            name='activity_pic',
            field=models.FileField(blank=True, help_text='活动图片', null=True, upload_to='activitypic/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 15, 12, 15, 154596), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 15, 12, 15, 157588), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 15, 12, 15, 156590), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hpic',
            name='url',
            field=models.FileField(blank=True, help_text='历史图片', null=True, upload_to='historypic/', verbose_name='历史图片'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 15, 12, 15, 155593), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
