# Generated by Django 2.2 on 2020-02-19 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_auto_20200219_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 26, 58, 131929), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='organ',
            field=models.ForeignKey(help_text='机构', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='user.Organ', verbose_name='机构'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 26, 58, 134921), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 26, 58, 133923), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 26, 58, 132926), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
