# Generated by Django 2.2 on 2020-03-10 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_auto_20200219_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 19, 25, 10, 969262), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='registration_time',
            field=models.DateField(blank=True, help_text='报名时间', null=True, verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 19, 25, 10, 972254), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 19, 25, 10, 971256), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 19, 25, 10, 970259), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
