# Generated by Django 2.2 on 2020-03-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_auto_20200310_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativity',
            name='hotcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ativity',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 9, 47, 324374), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 9, 47, 326370), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 9, 47, 326370), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userandactivity',
            name='signtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 9, 47, 325373), help_text='报名时间', verbose_name='报名时间'),
        ),
    ]
